# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-25 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20171025_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_kind',
            field=models.CharField(choices=[('dog', 'dog'), ('cat', 'cat')], max_length=3, verbose_name='kind of animal'),
        ),
    ]
